{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "todo.serviceAccountName" . }}
  labels:
{{ include "todo.labels" . | indent 4 }}
{{- end -}}
